### PR TITLE
Fix rendering of user errors on Python 3

### LINKED ISSUE #2: user.pt doesn't render exceptions on Python 3
Found this while porting zope.app.file.

It raises a UserError("some message") and expects that to get rendered. I verified that it does get caught by the publishing machinery and directed to the correct view. But that view is implemented in browser/user.pt like this:
```html
  <ul>
    <li tal:repeat="part context" tal:content="part"
        i18n:translate="">Error message</li>
  </ul>
```
That is, it wants to iterate on the context, which is an exception.

In Python 2, iterating the exception does this:
```pycon
(Pdb) pp list(iter(exception))
[u'The character set specified in the content type ($charset) does not match file content.']
```

But in Python 3, exceptions aren't iterable:
```pycon
(Pdb) pp list(iter(exception))
*** TypeError: 'UserError' object is not iterable
```

And so the tal expression does nothing and the message doesn't make it back to the user.

Thoughts on the best way to fix this?

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #2

### CODE REVIEW

**Comment by mgedmin** [comment]
I don't like that this makes `raise UserError('multiple', 'things')` act differently on Python 2 and 3.  Let's either drop support for iteration (with a prominent backwards-incompatibility notice in the changelog and a semver version bump), or implement `__iter__` on Python 3.

I think I prefer option 1.

**Comment by jamadden** [comment]
Wouldn't that still act the same on Python 2 and 3? They both have a `.args` that is `('multiple', 'things)`, so they would both iterate the same. It's not a behaviour change on Python 2, because `list(iter(UserError('multple', 'things')))` is the same as `list(iter(UserError('multiple', 'things').args))`.

**Comment by mgedmin** [comment]
Whoops, I misread the patch!

**Review by mgedmin — APPROVED** [review]
LGTM

**Comment by jamadden** [comment]
Thank you!

**Pull request merged**
